package_assets: off
template_function: _.template

javascripts:
  # Common javascript dependencies
  common:
    - public/javascripts/jquery-1.7.1.min.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/backbone.localStorage.js

  # Application specific javascript files
  backbone-queues:
    - src/mutex.js
    - src/queue.js
    - src/queues.js

